### ISSUE TITLE
Работа с новыми версиями SDK

### ISSUE THREAD

**Issue by Adigezalov** [lamantin-group/react-native-yandex-payment#11]
У ЯД сейчас версия SDK 3.5.0
При установке данной библиотеки получаю ошибку, что не может найти TMXProfiling
Будет ли обновление библиотеки и дальнейшая поддержка?

**Comment by whalemare** [comment]
Поддержка и обновление моими силами в ближайшее время не планируется, т.к. не стоит задач связанных с этим модулем (классический случай, в котором "на нашей машине все работает").
Проект открыт для ваших PR
