### ISSUE TITLE
Версия актуальна?

### ISSUE THREAD

**Issue by fof-fa** [lamantin-group/react-native-yandex-payment#19]
Здравствуйте.
Версия актуальна?
Это официальный релиз ЮКассы?
Не понятно `MyFramework` надо менять на `YandexPayment`?
В инструкции сказано _Open newly generated .xcworkspace in XCode and create new swift file. Be sure, that it have Foundation import_. Не понятно, как называть swift файл и куда его класть? Этот файл должен содержать строку `import Foundation`?
Не понятно, `TrustDefender` нужно спрашивать в Юкассе или нет?

**Comment by whalemare** [comment]
Здравствуйте, либа не официальная и поддерживается сообществом
1. Делать надо как в инструкции и в семплах
2. Название не обязательно, главное его наличие и импорта
3. TrustDefender нужно просить у кассы
